### ISSUE TITLE
Oven fan default value

### ISSUE THREAD

**Issue by MarshallAsch** [keeferrourke/pandoc-cookbook#2]
For the block:

```yaml
oven:
  fan: false
  temp: 425
  degrees: F
```
What is the default value for the `fan` field if it is not specified? `on`, `off`, or `false`? 

I know I could check but imo it would be nice to have in your usage doc.
